remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gem "github-pages", group: :jekyll_plugins
logo: /assets/img/headshot_circle.png


title: [Katherine Saavedra]
description: [Enthusiastic and detail-oriented analyst driving strategic decisions
and process optimization through advanced data analysis.
Empowering stakeholders with confident choices and delivering
actionable insights for remarkable success.]
